import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: { "2xl": "1400px" },
    },
    extend: {
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        display: ["Sora", "sans-serif"],
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        income: "hsl(var(--income))",
        expense: "hsl(var(--expense))",
        warning: "hsl(var(--warning))",
        violet: "hsl(var(--violet))",
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        "on-tertiary": "var(--on-tertiary)",
        "inverse-surface": "var(--inverse-surface)",
        "outline": "var(--outline)",
        "on-tertiary-fixed": "var(--on-tertiary-fixed)",
        "on-primary-fixed-variant": "var(--on-primary-fixed-variant)",
        "surface-tint": "var(--surface-tint)",
        "inverse-on-surface": "var(--inverse-on-surface)",
        "on-secondary": "var(--on-secondary)",
        "tertiary-fixed-dim": "var(--tertiary-fixed-dim)",
        "on-surface": "var(--on-surface)",
        "outline-variant": "var(--outline-variant)",
        "on-primary-fixed": "var(--on-primary-fixed)",
        "tertiary-fixed": "var(--tertiary-fixed)",
        "tertiary": "var(--tertiary)",
        "on-surface-variant": "var(--on-surface-variant)",
        "surface": "var(--surface)",
        "surface-dim": "var(--surface-dim)",
        "surface-container-highest": "var(--surface-container-highest)",
        "on-secondary-fixed-variant": "var(--on-secondary-fixed-variant)",
        "surface-container-low": "var(--surface-container-low)",
        "secondary-fixed-dim": "var(--secondary-fixed-dim)",
        "surface-container-high": "var(--surface-container-high)",
        "inverse-primary": "var(--inverse-primary)",
        "tertiary-container": "var(--tertiary-container)",
        "on-secondary-fixed": "var(--on-secondary-fixed)",
        "on-primary-container": "var(--on-primary-container)",
        "on-error-container": "var(--on-error-container)",
        "on-tertiary-fixed-variant": "var(--on-tertiary-fixed-variant)",
        "on-tertiary-container": "var(--on-tertiary-container)",
        "surface-bright": "var(--surface-bright)",
        "surface-variant": "var(--surface-variant)",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "surface-container": "var(--surface-container)",
        "error": "var(--error)",
        "on-primary": "var(--on-primary)",
        "on-error": "var(--on-error)",
        "primary-fixed": "var(--primary-fixed)",
        "primary-fixed-dim": "var(--primary-fixed-dim)",
        "error-container": "var(--error-container)",
        "primary-container": "var(--primary-container)",
        "on-background": "var(--on-background)",
        "secondary-fixed": "var(--secondary-fixed)",
        "on-secondary-container": "var(--on-secondary-container)",
        "secondary-container": "var(--secondary-container)"
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
